[workspace]
resolver = "2"
members = ["wasmtriggers-core","wasmtriggers-macros"]

[package]
name = "wasmtriggers-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
wasmtriggers-macros = { path = "wasmtriggers-macros" }
wasmtriggers-core = { path = "wasmtriggers-core" }

[[example]]
name = "coordinate_keybind"
crate-type = ["cdylib"]

[[example]]
name = "kitchen_sink"
crate-type = ["cdylib"]
